---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge
  hosts: all
  gather_facts: false # Must be disabled if target host has no or incompatible python interpreter.
  become: true
  strategy: free
  tasks:
    - name: Apply role under test
      ansible.builtin.include_role:
        name: eclipse_slm.python
